### ISSUE TITLE
Android - Location request dialog is needed

### ISSUE THREAD

**Issue by gamelaster** [aguilaair/IronOS-Companion#1]
Hey Eduardo, I tested the app today, and it looks amazing!

Although, on Android, it asks for access for nearby devices, but for successful scanning, it also needs Location permission request, which app doesn't ask for.

**Comment by aguilaair** [comment]
Hey! Happy to hear it, I will fix this asap. Sorry fo not having contacted you yet, it has been a really really crazy week

**Comment by aguilaair** [comment]
Should be solved now!
