### ISSUE TITLE
Pinecil V2 has erroneous temp spikes with IronOS companion

### ISSUE THREAD

**Issue by vguttmann** [aguilaair/IronOS-Companion#10]
**Describe the bug**

When using IronOS companion, sometimes the tip temperature spikes up to 450C for one time point (see screenshot). I'm not sure whether this is an IronOS or a companion bug, therefore I'm opening an issue in both repos.
![Screenshot_20240524-105154](https://github.com/Ralim/IronOS/assets/61903989/08b3310c-3514-4c77-bedf-01aac8f0086a)

**To Reproduce**

**Details of your device:**
 
 - Device: Pinecil V2
 - Release: V2.22E.C308FE8C
 - Power adapter being used: Lenovo 65W USB PD laptop charger

**Additional context**

Other issue: [https://github.com/Ralim/IronOS/issues/1915](https://github.com/Ralim/IronOS/issues/1915)

**Comment by aguilaair** [comment]
I'm inclined to say this is probably the packet that I am receiving from the Pinecil

**Comment by gamelaster** [comment]
so more likely to be issue on IronOS side I presume.

**Comment by aguilaair** [comment]
yep

**Comment by vguttmann** [comment]
> I'm inclined to say this is probably the packet that I am receiving from the Pinecil

Is there some way to log those messages, or get some debug information out of the installed app? I don't really fancy setting up the whole flutter toolchain again

Alternatively, is there a single binary that I can use to take a look at debug messages?

**Comment by aguilaair** [comment]
@vguttmann here is a debug build that prints the data that is parsed from the BLE packets:

https://wormhole.app/vjOJk#oF99qDNWfr06TugFlst7Lg (Expires in 24 hours, feel free to ask for another)

**Comment by vguttmann** [comment]
Okay, it's installed, but I'm not familiar with debugging android stuff, so I don't quite know how to get adb to give me the debug output

**Comment by vguttmann** [comment]
But at the least the bug still appears with the debug version, so I think this should be easy to solve

**Comment by vguttmann** [comment]
Well, attaching a debugger didn't print anything to the console. Can you push the code to Github (e.g. on a debug branch) so I can build it myself?

**Comment by aguilaair** [comment]
yeah sure

**Comment by aguilaair** [comment]
https://github.com/aguilaair/IronOS_Companion/tree/debugging

**Comment by vguttmann** [comment]
We got 'em.
I managed to capture a glitch, it's on line 759 in the attached file: 
```I/flutter (15025): New Data Update: IronData(currentTemp: 437, setpoint: 350, inputVoltage: 19.5, handleTemp: 37.5, power: 25, powerSrc: 3, tipResistance: 62, uptime: 919.4, lastMovementTime: 918.4, maxTemp: 460, rawTip: 10819, hallSensor: 0, currentMode: OperatingMode.soldering, estimatedWattage: 5.6)```

What's interesting is that the temp spikes don't always go up to the same temperature - they're close, but not exactly the same

One thing I had to do to get it to compile was to downgrade the rive package from `^0.12.4` to `^0.9.1`.


[debug.txt](https://github.com/aguilaair/IronOS_Companion/files/15467822/debug.txt)

**Comment by vguttmann** [comment]
I think that solves the issue from this side
