### ISSUE TITLE
Wrong package uri for Android

### ISSUE THREAD

**Issue by gamelaster** [aguilaair/IronOS-Companion#2]
It uses com.example.ironos_companion , but after recreation, it uses correct one, but creates collision.

**Comment by aguilaair** [comment]
I cannot replicate this, and the code has no references to `com.example`, so it was probably a weird Flutter issue

**Comment by gamelaster** [comment]
Sorry, I noticed it just now, the problem is in the path to the MainActivity.kt file. When the Flutter re-generates Android platform, it creates good path, thus making two MainActivity.kt.

/android/app/src/main/kotlin/**com/example**/ironos_companion
