### ISSUE TITLE
Not in the Play Store ;)

### ISSUE THREAD

**Issue by agibson2** [aguilaair/IronOS-Companion#3]
I am just creating this so that I don't miss when/if it gets into the Apple appstore ;) :) :).  Thanks for creating this app.  It really looks amazing.  The history graph will be very useful.

If you charge $ for it,  I will certainly buy it just for the convenience of it being easily available without the need to sideload it in developer mode.... which I can't do on my company phone.

Subscribed! ;)

**Comment by aguilaair** [comment]
I won't be charging for it, it should also be released pretty soon, stay tuned!

**Comment by gamelaster** [comment]
@agibson2 https://apps.apple.com/us/app/ironos-companion/id6469055544 😊 
Thanks to Pine Store, they provided us their App Store account so we were able to publish it.

**Comment by aguilaair** [comment]
Now we just have the Play Store left!

**Comment by TheBest6337** [comment]
Still waiting for the play store

**Comment by aguilaair** [comment]
@gamelaster any updates on getting it on the Play Store?

**Comment by gamelaster** [comment]
> @gamelaster any updates on getting it on the Play Store?

In upcoming weeks, I will try to deploy the app to Google Play. Sorry, was too busy :(

**Comment by gamelaster** [comment]
Sorry, January was too busy, will try in upcoming days.

**Comment by gamelaster** [comment]
https://play.google.com/store/apps/details?id=dev.eduardom.ironos_companion it's finally published! Sorry for waiting.

**Comment by aguilaair** [comment]
Awesome, I'm going to close this issue now then!

**Comment by lunananananananana** [comment]
having it on F-Droid would also be nice, I prefer installing open source apps from there whenever possible

**Comment by aguilaair** [comment]
https://github.com/aguilaair/IronOS_Companion/issues/11
